# Generated by Django 5.2.7 on 2025-10-15 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_bvn_user_nin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="bvn",
            field=models.CharField(
                default=123456789012345, max_length=128, unique=True
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="nin",
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
