# Generated by Django 5.2.7 on 2025-10-15 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_wallet_bvn"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallet",
            name="bvn",
            field=models.CharField(default=0, max_length=128, unique=True),
            preserve_default=False,
        ),
    ]
