# Generated by Django 5.2.7 on 2025-10-21 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_transactionhistory_balance_after_transaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="transactionhistory",
            name="narration",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
