# Generated by Django 5.2.7 on 2025-10-27 14:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "card_number",
                    models.CharField(editable=False, max_length=16, unique=True),
                ),
                (
                    "card_type",
                    models.CharField(
                        choices=[
                            ("visa", "Visa"),
                            ("verve", "Verve"),
                            ("master card", "Master Card"),
                            ("american express", "American Express"),
                        ],
                        default="master card",
                        max_length=20,
                    ),
                ),
                ("card_expiry_date", models.CharField(editable=False, max_length=5)),
                ("cvv", models.CharField(editable=False, max_length=3)),
                (
                    "pin_hash",
                    models.CharField(help_text="Hashed card PIN", max_length=128),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "balance",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_used", models.DateTimeField(blank=True, null=True)),
                (
                    "daily_limit",
                    models.DecimalField(
                        decimal_places=2, default=500000.0, max_digits=10
                    ),
                ),
                (
                    "daily_spend",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("last_reset", models.DateField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
